import {Devis} from "./devis";

export class Notification {
  // private _type: string;
  // private _description: string;
  // private _lu: boolean;

  // _id: string;
  type: string;
  description: string;
  lue: boolean;
  devis: Devis;

  // constructor(type: string, description: string, lu: boolean) {
  //   this._type = type;
  //   this._description = description;
  //   this._lu = lu;
  // }
}
